### ISSUE TITLE
Concord doesn't work with JDK 16

### ISSUE THREAD

**Issue by ibodrov** [walmartlabs/concord#415]
```
> java --version
openjdk 16 2021-03-16
OpenJDK Runtime Environment Zulu16.28+11-CA (build 16+36)
OpenJDK 64-Bit Server VM Zulu16.28+11-CA (build 16+36, mixed mode, sharing)
```

```
> concord run                                                                                                                                                                                                 Copying files into the target directory...
Starting...
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3973)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4957)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4963)
        at com.google.inject.internal.FailableCache.get(FailableCache.java:54)
        at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
        at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:155)
        at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:592)
        at com.google.inject.internal.AbstractBindingProcessor$Processor.initializeBinding(AbstractBindingProcessor.java:173)
        at com.google.inject.internal.AbstractBindingProcessor$Processor.lambda$scheduleInitialization$0(AbstractBindingProcessor.java:160)
        at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:49)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:124)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at com.walmartlabs.concord.runtime.v2.runner.InjectorFactory.create(InjectorFactory.java:105)
        at com.walmartlabs.concord.cli.Run.call(Run.java:223)
        at com.walmartlabs.concord.cli.Run.call(Run.java:1)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at com.walmartlabs.concord.cli.Main.main(Main.java:29)
Caused by: java.lang.IllegalStateException: Unable to load cache item
        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:79)
        at com.google.inject.internal.cglib.core.internal.$LoadingCache.get(LoadingCache.java:34)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:294)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:258)
        at com.google.inject.internal.BytecodeGen.newFastClassForMember(BytecodeGen.java:207)
        at com.google.inject.internal.DefaultConstructionProxyFactory.create(DefaultConstructionProxyFactory.java:49)
        at com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:156)
        at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:94)
        at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:30)
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:38)
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:34)
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:43)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2276)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2154)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2044)
        ... 27 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
        at com.google.inject.internal.cglib.core.$DuplicatesPredicate.evaluate(DuplicatesPredicate.java:104)
        at com.google.inject.internal.cglib.core.$CollectionUtils.filter(CollectionUtils.java:52)
        at com.google.inject.internal.cglib.reflect.$FastClassEmitter.<init>(FastClassEmitter.java:69)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.generateClass(FastClass.java:77)
        at com.google.inject.internal.cglib.core.$DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.generate(AbstractClassGenerator.java:332)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
        at com.google.inject.internal.cglib.core.internal.$LoadingCache$2.call(LoadingCache.java:54)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at com.google.inject.internal.cglib.core.internal.$LoadingCache.createEntry(LoadingCache.java:61)
        ... 44 more
```

**Comment by ibodrov** [comment]
Leaving it here, so I won't forget to look into this.

**Comment by jmclean-starburst** [comment]
Im hitting this issue as well

**Comment by ibodrov** [comment]
Should be fixed by https://github.com/walmartlabs/concord/pull/429

**Comment by ibodrov** [comment]
> I have been trying to start an agent using JDK16 with no luck.
I'll look into it.

**Comment by jmclean-starburst** [comment]
@ibodrov would you like a different issue that is more specific to the agent issue so this once can be closed out, or do you think piling in on this is ok?

**Comment by ibodrov** [comment]
@jmclean-starburst I renamed the issue. Looks like the same problem affects the CLI, the agent and the server.
Well, basically all modules that are using Guava.

**Comment by ibodrov** [comment]
@jmclean-starburst I pushed https://github.com/walmartlabs/concord/pull/429/commits/f583e25117299b4c0c4d0eb6297014107a1a13f2

Basically, for the Guava version we're using, we need to either add `--add-opens` to the `java` command or add `Add-Opens` to the main JAR's `MANIFEST.MF`. Unfortunately, the latter doesn't work for multi-JAR apps (not sure why). And `--add-opens` doesn't work on Java 8. Which means we need to check for the JDK version in the start scripts and add command line parameters accordingly. :P

**Comment by jmclean-starburst** [comment]
@ibodrov This may be our agent config issue, as for some reason I had to add `server.apiKey` config value to the agents `default.conf` to start the agent service, but now i get the below error after the work is accepted by an agent (agent logs):
```
java.lang.IncompatibleClassChangeError: Method 'com.walmartlabs.concord.imports.ImmutableSecretDefinition$Builder com.walmartlabs.concord.impor
Jun 21 16:14:31 ip-10-10-13-80 bash[20231]:         at com.walmartlabs.concord.agent.Worker.getSecret(Worker.java:176)
Jun 21 16:14:31 ip-10-10-13-80 bash[20231]:         at com.walmartlabs.concord.agent.Worker.lambda$0(Worker.java:161)
Jun 21 16:14:31 ip-10-10-13-80 bash[20231]:         at com.walmartlabs.concord.agent.Worker.withTimer(Worker.java:226)
Jun 21 16:14:31 ip-10-10-13-80 bash[20231]:         at com.walmartlabs.concord.agent.Worker.fetchRepo(Worker.java:155)
Jun 21 16:14:31 ip-10-10-13-80 bash[20231]:         at com.walmartlabs.concord.agent.Worker.run(Worker.java:81)
Jun 21 16:14:31 ip-10-10-13-80 bash[20231]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Jun 21 16:14:31 ip-10-10-13-80 bash[20231]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Jun 21 16:14:31 ip-10-10-13-80 bash[20231]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
Jun 21 16:14:31 ip-10-10-13-80 bash[20231]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
Jun 21 16:14:31 ip-10-10-13-80 bash[20231]:         at java.base/java.lang.Thread.run(Thread.java:831)
```

Not sure if this is tied to the jdk16 stuff, but its the error i am now encountering after adding the `--add-opens` flag to the config file.

**Comment by ibodrov** [comment]
@jmclean-starburst I was able to run the server and the agent directly in IDE and start a process. I didn't get the error you posted, but it failed with the same Guava's "Unable to load cache item" error.

It looks like the JDK 16 support still needs some work. I'll open a new ticket with all the findings so far.

**Comment by ibodrov** [comment]
https://github.com/walmartlabs/concord/issues/431
